InternetCafe/InternetCafe/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using InternetCafe.Data;
using InternetCafe.Models;
using InternetCafe.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace InternetCafe.Controllers
{
    [Authorize]
    public class ReservationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReservationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Reservations
        public async Task<IActionResult> Index()
        {
            return View(await _context.Reservations.ToListAsync());
        }

        // GET: Reservations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // GET: Reservations/Create
        public IActionResult Create()
        {
            CreateReservationViewModel model = new CreateReservationViewModel();
            model.Devices = _context.Devices.ToList();
            model.IRLs = _context.IRLs.ToList();
            model.VIPs = _context.VIPs.ToList();
            return View(model);
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateReservationViewModel reservation)
        {
            Reservation r = new Reservation();
            r.Name = reservation.Name;
            r.Date = reservation.Date;
            r.StartTime = reservation.StartTime;
            r.EndTime = reservation.EndTime;
            r.Customer = reservation.Customer;
            r.VIP = _context.VIPs.Where(x => x.Id == reservation.VIPId).FirstOrDefault();
            r.Device = _context.Devices.Where(x => x.Id == reservation.DeviceId).FirstOrDefault();
            r.IRL = _context.IRLs.Where(x => x.Id == reservation.IRLId).FirstOrDefault();

            if (ModelState.IsValid)
            {
                _context.Add(r);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations.FindAsync(id);
            if (reservation == null)
            {
                return NotFound();
            }
            CreateReservationViewModel model = new CreateReservationViewModel();
            model.Name = reservation.Name;
            model.Date = reservation.Date;
            model.Customer = reservation.Customer;
            model.StartTime = reservation.StartTime;
            model.EndTime = reservation.EndTime;

            model.Devices = _context.Devices.ToList();
            model.IRLs = _context.IRLs.ToList();
            model.VIPs = _context.VIPs.ToList();
            return View(model);

            
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,  CreateReservationViewModel reservation)
        {
            if (id != reservation.Id)
            {
                return NotFound();
            }

            Reservation oldReservation = _context.Reservations.Where(x => x.Id == reservation.Id).FirstOrDefault();
            oldReservation.Name = reservation.Name;
            oldReservation.Date = reservation.Date;
            oldReservation.Customer = reservation.Customer;
            oldReservation.StartTime = reservation.StartTime;
            oldReservation.EndTime = reservation.EndTime;
            oldReservation.Device = _context.Devices.Where(x => x.Id == reservation.DeviceId).FirstOrDefault();
            oldReservation.VIP = _context.VIPs.Where(x => x.Id == reservation.VIPId).FirstOrDefault();
            oldReservation.IRL = _context.IRLs.Where(x => x.Id == reservation.IRLId).FirstOrDefault();
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        // GET: Reservations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservations
                .FirstOrDefaultAsync(m => m.Id == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reservation = await _context.Reservations.FindAsync(id);
            _context.Reservations.Remove(reservation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
            return _context.Reservations.Any(e => e.Id == id);
        }
    }
}

InternetCafe/InternetCafe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InternetCafe</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color:black">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InternetCafe</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">
                                Make a Reservation
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="color:ivory">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - InternetCafe - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>